import type { Metadata } from "next";
import { Bebas_Neue, Montserrat } from "next/font/google";
import Nav from "@/app/components/Nav/Nav";
import "./globals.scss";

export const metadata: Metadata = {
  title: "BetterLogs",
  description: "Generated by create next app",
};

const bebasNeue = Bebas_Neue({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-bebas-neue",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-montserrat",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bebasNeue.variable} ${montserrat.variable}`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
