import type { Metadata } from "next";
import Nav from "@/app/components/Nav.js";
import "./globals.scss";

export const metadata: Metadata = {
  title: "BetterLogs",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <p>Environment: {process.env.VERCEL_ENV}</p>
        <Nav />
        {children}
      </body>
    </html>
  );
}
